### ISSUE TITLE
Reduce duplicated utilities

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/vaul-vue#12]
Thanks for take care of porting vaul to Vue

---

**`radix-vue`** uses **`@vueuse/core`** underhood so why not use their utility functions?

> why not using our local utility functions?

They have same logic why not replace them with already defined utility in `@vueuse/core`? we can prevent duplication by doing this

| Local utils | @vueuse/core utils |
|--------|--------|
| [isIOS function](https://github.com/Elliot-Alexander/vaul-vue/blob/main/packages/vaul-vue/src/scroll/platformTests.ts#L25) | `isIOS` expression  |
| [addEvent](https://github.com/Elliot-Alexander/vaul-vue/blob/main/packages/vaul-vue/src/scroll/util.ts#L41) | [useEventListener](https://vueuse.org/core/useEventListener/) |
| [set](https://github.com/Elliot-Alexander/vaul-vue/blob/main/packages/vaul-vue/src/scroll/util.ts#L57) function CSS| maybe [useCssVar](https://vueuse.org/core/useCssVar/) I'm not sure about this one | 

Or other local utility which I can't recognize the equivalent in @vueuse/core

**Comment by Elliot-Alexander** [comment]
Yeah I think this a great idea, cleans up quite a few utility functions :D

**Comment by Elliot-Alexander** [comment]
Going through this, I have a suspicion that we can remove a lot of the util if we use the `useScrollLock` as it appears to resolve most of what those utils work to achieve. @connerblanton what are your thoughts? I raised #21 which includes this change and tested on old iPhone 8 I have (couldn't see any issues but that phone is relatively old)

**Comment by connerblanton** [comment]
I think we can definitely do this. However, I do see a problem (I don't think it's caused by this, rather we just have some more work to do for it) when there are inputs and scrollable content. I took the code from the [Scrollable with inputs](https://codesandbox.io/p/sandbox/drawer-with-scale-forked-73f8jw?file=%2Fapp%2Fmy-drawer.tsx%3A1%2C1) example from Vaul. When I test this example on ours, we automatically focus on the first input and when the keyboard is up, I am able to scroll and the page refreshes (on Safari) when I pull down.

Again, I think we can still use this, but we also need to make this example work

**Comment by Elliot-Alexander** [comment]
Ah I see, so this is limited to when the drawer is scrollable and contains input field(s)? You're right then, we'll definitely have to do some work on this
